### ISSUE TITLE
Syntax-error in package.json

### ISSUE THREAD

**Issue by Cheeeeeeeeeese** [TrueGRF/TrueGRF#74]
Everytime I run the npm run build command the terminal spits out the error message "syntax-error".

```
PS C:\Users\phils\Downloads\TrueGRF-3.1.0> npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Debugger attached.

> truegrf@dev build
> copy node_modules/carbon-components-svelte/css/*.css static/ && svelte-kit build

Syntaxfehler.
Waiting for the debugger to disconnect...
```

Maybe the solution is very simple but I never worked with node.js or web-development in general.

**Comment by TrueBrain** [comment]
I think what you run into that TrueGRF is meant to be build on Linux, not Windows. And as I don't develop on Windows, I also have no clue how to address. You can give it a spin if you like, but I will not be of much help to you, sorry.

PS: just as reminder, unless you want to develop new functionalities for TrueGRF, there is no need to build TrueGRF yourself. You can just visit https://truegrf.truebrain.nl/ to use TrueGRF as user.

**Comment by Cheeeeeeeeeese** [comment]
My god I am stupid. I did not even know there is a Website for it. I thought one had to download it to use it. 
Thank you.

**Comment by Cheeeeeeeeeese** [comment]
Again thank you
