### ISSUE TITLE
Town names UI keeps becoming non responsive.

### ISSUE THREAD

**Issue by StarRaid** [TrueGRF/TrueGRF#75]
This happens when you click "+ New Townname" or create a new subset. Seems to be most reproducable if you keep creating new things without naming the new things. This has somehow rendered [my project](https://github.com/StarRaid/testownames) unusable. If click on any of the set names it freezes now.

The list of town name sets
![image](https://user-images.githubusercontent.com/36111067/174114036-26ab46a9-2704-4b8c-a463-29501360ad24.png)

If I click any of them, the UI stays like this, with two sets selected at once.
![image](https://user-images.githubusercontent.com/36111067/174114151-7b6f1f57-d06f-40b7-abe2-98e6a659be6e.png)

I have not been able to reproduce any of these bugs in a new set using the black template.

**Comment by TrueBrain** [comment]
Steps to reproduce: create a new townname, create a new set, click on main, click on set, crash.

Investigating what is actually going on :)

**Comment by TrueBrain** [comment]
Part of v3.1.1. If you have any broken townname, click on it, go to Names, and create a new part in the mainset. That should fix that townname.

Tnx for the report, this was very useful information :D
