### ISSUE TITLE
Can't start under Windows

### ISSUE THREAD

**Issue by SylvainDevidal** [TrueGRF/TrueGRF#77]
When trying to run the program it fails with a "cp" command not found :

```
E:\Programmes\TrueGRF>npm run build

> truegrf@dev build
> cp node_modules/carbon-components-svelte/css/*.css static/ && svelte-kit build

'cp' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

You may detect which OS is being executed then adapt fix the commands

**Comment by TrueBrain** [comment]
I think what you run into that TrueGRF is meant to be build on Linux, not Windows. And as I don't develop on Windows, I also have no clue how to address this issue. You can give it a spin if you like, but I will not be of much help to you, sorry.

PS: just as reminder, unless you want to develop new functionalities for TrueGRF, there is no need to build TrueGRF yourself. You can just visit https://truegrf.truebrain.nl/ to use TrueGRF as user.
